# Generated by Django 3.0.3 on 2020-02-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0003_auto_20200221_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='data',
            name='data_file',
            field=models.FileField(blank=True, upload_to='repo_data'),
        ),
    ]
