# Generated by Django 3.0.3 on 2020-02-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0004_auto_20200224_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data_file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
