# Generated by Django 3.0.3 on 2020-02-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0005_auto_20200224_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data_file',
            field=models.ImageField(upload_to='documents/'),
        ),
    ]
