# Generated by Django 3.0.3 on 2020-02-26 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_userprofileinfo'),
        ('repo', '0008_data_upload_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='data_file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
